import theme from "./theme";

const baseLayers = [
    {
        id: "background",
        type: "background",
        layout: {
            visibility: "visible",
        },
        paint: {
            "background-color": theme.color.background,
        },
    },
    {
        id: "landuse_classes",
        type: "fill",
        source: "openmaptiles",
        "source-layer": "landuse",
        minzoom: 7,
        layout: {
            visibility: "visible",
        },
        paint: {
            "fill-color": ["match", ["get", "class"], "stadium", theme.color.parkGreen, "pitch", theme.color.parkGreen, "playground", theme.color.parkGreen, theme.color.background],
            "fill-opacity": 1,
        },
        metadata: {},
        filter: ["all", ["in", "class", "stadium", "pitch", "playground"], ["==", "$type", "Polygon"]],
    },
    {
        id: "landcover_classes",
        type: "fill",
        source: "openmaptiles",
        "source-layer": "landcover",
        maxzoom: 13,
        layout: {
            visibility: "visible",
        },
        paint: {
            "fill-color": [
                "match",
                ["get", "class"],
                "farmland",
                theme.color.farmland,
                "wood",
                theme.color.green,
                "grass",
                theme.color.green,
                "sand",
                theme.color.sand,
                "wetland",
                theme.color.green,
                theme.color.background,
            ],
            "fill-opacity": {
                stops: [
                    [7, 0.5],
                    [10, 1],
                ],
            },
            "fill-antialias": false,
        },
        metadata: {},
        filter: ["all", ["in", "class", "farmland", "wood", "grass", "wetland", "sand"]],
    },
    {
        id: "landcover_park",
        type: "fill",
        source: "openmaptiles",
        "source-layer": "landcover",
        minzoom: 13,
        layout: {
            visibility: "visible",
        },
        paint: {
            "fill-color": theme.color.parkGreen,
            "fill-antialias": true,
        },
        filter: ["all", ["==", "subclass", "park"]],
    },
    {
        id: "landcover_subclasses",
        type: "fill",
        source: "openmaptiles",
        "source-layer": "landcover",
        minzoom: 13,
        layout: {
            visibility: "visible",
        },
        paint: {
            "fill-color": [
                "match",
                ["get", "subclass"],
                "allotments",
                theme.color.parkGreen,
                "beach",
                theme.color.sand,
                "dune",
                theme.color.sand,
                "scrub",
                theme.color.green,
                "farm",
                theme.color.farmland,
                "farmland",
                theme.color.farmland,
                "forest",
                theme.color.green,
                "grass",
                theme.color.green,
                "grassland",
                theme.color.green,
                "golf_course",
                theme.color.parkGreen,
                "heath",
                theme.color.green,
                "mangrove",
                theme.color.green,
                "meadow",
                theme.color.farmland,
                "orchard",
                theme.color.farmland,
                "park",
                theme.color.parkGreen,
                "garden",
                theme.color.parkGreen,
                "plant_nursery",
                theme.color.farmland,
                "recreation_ground",
                theme.color.farmland,
                "reedbed",
                theme.color.green,
                "sand",
                theme.color.sand,
                "swamp",
                theme.color.green,
                "tidalflat",
                theme.color.sand,
                "village_green",
                theme.color.green,
                "vineyard",
                theme.color.farmland,
                "wet_meadow",
                theme.color.green,
                "wetland",
                theme.color.green,
                "wood",
                theme.color.green,
                "marsh",
                theme.color.green,
                theme.color.background,
            ],
            "fill-antialias": true,
        },
        filter: [
            "all",
            [
                "in",
                "subclass",
                "allotments",
                "beach",
                "dune",
                "scrub",
                "farm",
                "farmland",
                "forest",
                "garden",
                "grass",
                "grassland",
                "golf_course",
                "heath",
                "meadow",
                "orchard",
                "plant_nursery",
                "recreation_ground",
                "reedbed",
                "saltmarsh",
                "sand",
                "scree",
                "swamp",
                "tidalflat",
                "tundra",
                "village_green",
                "vineyard",
                "wet_meadow",
                "wetland",
                "wood",
            ],
        ],
    },
    {
        id: "national_parks",
        type: "line",
        source: "openmaptiles",
        "source-layer": "park",
        minzoom: 8,
        layout: {
            visibility: "visible",
        },
        paint: {
            "line-color": theme.color.parkGreen,
            "line-width": {
                base: 1,
                stops: [
                    [8, 1.2],
                    [9, 1.5],
                    [10, 3.6],
                    [24, 3.6],
                ],
            },
            "line-offset": 1,
            "line-opacity": 0.8,
        },
    },
    {
        id: "waterway_tunnel",
        type: "line",
        source: "openmaptiles",
        "source-layer": "waterway",
        minzoom: 14,
        layout: {
            "line-cap": "round",
            visibility: "visible",
        },
        paint: {
            "line-color": theme.color.water,
            "line-width": {
                base: 1.3,
                stops: [
                    [13, 0.5],
                    [20, 6],
                ],
            },
            "line-dasharray": [2, 4],
        },
        filter: ["all", ["==", "brunnel", "tunnel"]],
    },
    {
        id: "waterway_river",
        type: "line",
        source: "openmaptiles",
        "source-layer": "waterway",
        layout: {
            "line-cap": "round",
            visibility: "visible",
        },
        paint: {
            "line-color": theme.color.water,
            "line-width": {
                base: 1.2,
                stops: [
                    [11, 0.5],
                    [20, 6],
                ],
            },
        },
        metadata: {},
        filter: ["all", ["==", "class", "river"], ["!=", "brunnel", "tunnel"], ["!=", "intermittent", 1]],
    },
    {
        id: "waterway_river_intermittent",
        type: "line",
        source: "openmaptiles",
        "source-layer": "waterway",
        layout: {
            "line-cap": "round",
        },
        paint: {
            "line-color": theme.color.water,
            "line-width": {
                base: 1.2,
                stops: [
                    [11, 0.5],
                    [20, 6],
                ],
            },
            "line-dasharray": [3, 2],
        },
        metadata: {},
        filter: ["all", ["==", "class", "river"], ["!=", "brunnel", "tunnel"], ["==", "intermittent", 1]],
    },
    {
        id: "waterway_other",
        type: "line",
        source: "openmaptiles",
        "source-layer": "waterway",
        layout: {
            "line-cap": "round",
            visibility: "visible",
        },
        paint: {
            "line-color": theme.color.water,
            "line-width": {
                base: 1.3,
                stops: [
                    [13, 0.5],
                    [20, 6],
                ],
            },
        },
        metadata: {},
        filter: ["all", ["!=", "class", "river"], ["!=", "brunnel", "tunnel"], ["!=", "intermittent", 1]],
    },
    {
        id: "waterway_other_intermittent",
        type: "line",
        source: "openmaptiles",
        "source-layer": "waterway",
        layout: {
            "line-cap": "round",
            visibility: "visible",
        },
        paint: {
            "line-color": theme.color.water,
            "line-width": {
                base: 1.3,
                stops: [
                    [13, 0.5],
                    [20, 6],
                ],
            },
            "line-dasharray": [4, 3],
        },
        metadata: {},
        filter: ["all", ["!=", "class", "river"], ["!=", "brunnel", "tunnel"], ["==", "intermittent", 1]],
    },
    {
        id: "water_intermittent",
        type: "fill",
        source: "openmaptiles",
        "source-layer": "water",
        layout: {
            visibility: "visible",
        },
        paint: {
            "fill-color": theme.color.water,
            "fill-opacity": 0.85,
        },
        metadata: {},
        filter: ["all", ["==", "intermittent", 1]],
    },
    {
        id: "water",
        type: "fill",
        source: "openmaptiles",
        "source-layer": "water",
        layout: {
            visibility: "visible",
        },
        paint: {
            "fill-color": theme.color.water,
        },
        metadata: {},
        filter: ["all", ["!=", "intermittent", 1], ["!=", "brunnel", "tunnel"]],
    },
];

export default baseLayers;
