import theme from "./theme";

const labelLayers = (lang) => [
    {
        id: "water_way_name",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "waterway",
        minzoom: 0,
        layout: {
            "text-font": theme.text.fontFamily(lang),
            "text-size": {
                stops: [
                    [11, 10],
                    [13, 12],
                ],
            },
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "symbol-spacing": 400,
            "text-max-width": 5,
            "symbol-placement": "line",
        },
        paint: {
            "text-color": theme.textColor.water,
            "text-halo-color": "rgba(255,255,255,0.7)",
            "text-halo-width": 1,
        },
        metadata: {},
        filter: ["all", ["==", "$type", "LineString"]],
    },
    {
        id: "water_name_line",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "water_name",
        minzoom: 0,
        layout: {
            "text-font": theme.text.fontFamily(lang),
            "text-size": 12,
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "text-max-width": 5,
            "symbol-placement": "line",
        },
        paint: {
            "text-color": theme.textColor.water,
            "text-halo-color": "rgba(255,255,255,0.7)",
            "text-halo-width": 1,
        },
        metadata: {},
        filter: ["all", ["==", "$type", "LineString"]],
    },
    {
        id: "water_name_point",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "water_name",
        minzoom: 16,
        maxzoom: 24,
        layout: {
            "text-font": theme.text.fontFamily(lang),
            "text-size": 11,
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "text-max-width": 5,
        },
        paint: {
            "text-color": theme.textColor.water,
            "text-halo-color": "rgba(255,255,255,0.7)",
            "text-halo-width": 1,
        },
        metadata: {},
        filter: ["all", ["==", "$type", "Point"], ["!=", "class", "ocean"]],
    },
    {
        id: "poi_shop-z17",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "poi",
        minzoom: 0,
        layout: {
            "text-font": theme.text.fontFamily(lang),
            "text-size": {
                stops: [
                    [15, 10],
                    [20, 11],
                ],
            },
            "icon-image": "{subclass}",
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "text-anchor": "top",
            "text-offset": [0, 1.1],
            "text-padding": 2,
            "text-max-width": 9,
            "icon-allow-overlap": true,
        },
        paint: {
            "text-color": ["match", ["get", "class"], "ice_cream", "#C77400", "#939"],
            "icon-opacity": 1,
            "icon-halo-blur": 1,
            "text-halo-blur": 0.5,
            "icon-halo-color": "rgba(255, 255, 255, 1)",
            "icon-halo-width": 0.5,
            "text-halo-color": "#ffffff",
            "text-halo-width": 1,
        },
        metadata: {},
        filter: ["all", ["in", "class", "shop", "clothing_store", "library", "art_gallery", "music", "alcohol_shop", "bakery"], ["!in", "subclass", "mall", "library", "artwork"]],
    },
    {
        id: "poi_shop-z15",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "poi",
        minzoom: 0,
        layout: {
            "text-font": theme.text.fontFamily(lang),
            "text-size": {
                stops: [
                    [15, 10],
                    [20, 11],
                ],
            },
            "icon-image": "{subclass}",
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "text-anchor": "top",
            "text-offset": [0, 1.1],
            "text-padding": 2,
            "text-max-width": 9,
            "icon-allow-overlap": true,
        },
        paint: {
            "text-color": ["match", ["get", "class"], "ice_cream", "#C77400", "#939"],
            "icon-opacity": 1,
            "icon-halo-blur": 1,
            "text-halo-blur": 0.5,
            "icon-halo-color": "rgba(255, 255, 255, 1)",
            "icon-halo-width": 0.5,
            "text-halo-color": "#ffffff",
            "text-halo-width": 1,
        },
        metadata: {},
        filter: ["all", ["==", "subclass", "supermarket"]],
    },
    {
        id: "poi_waste",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "poi",
        minzoom: 0,
        layout: {
            "text-font": theme.text.fontFamily(lang),
            "text-size": {
                stops: [
                    [15, 10],
                    [20, 11],
                ],
            },
            "icon-image": "{subclass}",
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "text-anchor": "top",
            "text-offset": [0, 0.8],
            "text-padding": 2,
            "text-max-width": 9,
            "icon-allow-overlap": false,
        },
        paint: {
            "text-color": "#734a08",
            "icon-opacity": 1,
            "icon-halo-blur": 1,
            "text-halo-blur": 0.5,
            "icon-halo-color": "rgba(255, 255, 255, 1)",
            "icon-halo-width": 0.5,
            "text-halo-color": "#ffffff",
            "text-halo-width": 1,
        },
        metadata: {},
        filter: ["all", ["in", "class", "recycling", "waste_basket", "drinking_water", "toilets"]],
    },
    {
        id: "poi_cemetery",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "poi",
        minzoom: 0,
        layout: {
            "icon-size": 1,
            "text-font": theme.text.fontFamily(lang),
            "text-size": 11,
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "icon-anchor": "bottom",
            "icon-offset": [0, 0],
            "text-anchor": "center",
            "text-offset": [0, 0],
            "text-padding": 2,
            "icon-text-fit": "none",
            "text-max-width": 14,
            "icon-allow-overlap": false,
            "icon-pitch-alignment": "viewport",
        },
        paint: {
            "text-color": "#2d4931",
            "icon-translate": [0, 0],
            "text-translate": [0, 5],
            "text-halo-color": "rgba(255, 255, 255, 1)",
            "text-halo-width": 0.8,
            "icon-translate-anchor": "map",
            "text-translate-anchor": "viewport",
        },
        metadata: {},
        filter: ["all", ["in", "class", "cemetery"]],
    },
    {
        id: "poi_school",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "poi",
        minzoom: 15,
        layout: {
            "icon-size": 1,
            "text-font": theme.text.fontFamily(lang),
            "text-size": 11,
            "icon-image": "{subclass}",
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "icon-anchor": "bottom",
            "icon-offset": [0, 0],
            "text-anchor": "center",
            "text-offset": [0, 0],
            "text-padding": 2,
            "icon-text-fit": "none",
            "text-max-width": 9,
            "icon-allow-overlap": false,
            "icon-pitch-alignment": "viewport",
        },
        paint: {
            "text-color": "#4d4d00",
            "icon-translate": [0, 0],
            "text-translate": [0, 5],
            "text-halo-color": "rgba(255, 255, 255, 1)",
            "text-halo-width": 0.8,
            "icon-translate-anchor": "map",
            "text-translate-anchor": "viewport",
        },
        metadata: {},
        filter: ["all", ["in", "class", "college", "school"]],
    },
    {
        id: "poi_outdoor",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "poi",
        minzoom: 0,
        layout: {
            "text-font": theme.text.fontFamily(lang),
            "text-size": {
                stops: [
                    [15, 10],
                    [20, 11],
                ],
            },
            "icon-image": "{subclass}",
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "text-anchor": "top",
            "text-offset": [0, 1.2],
            "text-padding": 2,
            "text-max-width": 9,
            "icon-allow-overlap": false,
        },
        paint: {
            "text-color": "#008c0d",
            "icon-opacity": 1,
            "text-halo-blur": 0,
            "text-halo-color": "#ffffff",
            "text-halo-width": 1,
        },
        metadata: {},
        filter: ["all", ["in", "class", "playground", "stile", "garden", "gate"]],
    },
    {
        id: "poi_golf",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "poi",
        minzoom: 16,
        layout: {
            "text-font": theme.text.fontFamily(lang),
            "text-size": {
                stops: [
                    [15, 10],
                    [20, 11],
                ],
            },
            "icon-image": "golf",
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "text-anchor": "top",
            "text-offset": [0, 1.2],
            "text-padding": 2,
            "text-max-width": 9,
            "icon-allow-overlap": false,
        },
        paint: {
            "text-color": "#008c0d",
            "icon-opacity": 1,
            "icon-halo-blur": 1,
            "text-halo-blur": 0.5,
            "icon-halo-color": "rgba(255, 255, 255, 1)",
            "icon-halo-width": 0.5,
            "text-halo-color": "#ffffff",
            "text-halo-width": 1,
        },
        metadata: {},
        filter: ["all", ["in", "class", "golf"]],
    },
    {
        id: "poi_sport",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "poi",
        minzoom: 0,
        layout: {
            "text-font": theme.text.fontFamily(lang),
            "text-size": {
                stops: [
                    [15, 10],
                    [20, 11],
                ],
            },
            "icon-image": "{subclass}",
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "text-anchor": "top",
            "text-offset": [0, 1.2],
            "text-padding": 2,
            "text-max-width": 9,
            "icon-allow-overlap": false,
        },
        paint: {
            "text-color": "#008c0d",
            "icon-opacity": 1,
            "icon-halo-blur": 0,
            "text-halo-blur": 1,
            "text-halo-color": "#ffffff",
            "text-halo-width": 0.2,
        },
        metadata: {},
        filter: ["all", ["in", "class", "stadium", "swimming_pool", "sports_centre", "water_park"]],
    },
    {
        id: "poi_food",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "poi",
        minzoom: 0,
        layout: {
            "text-font": theme.text.fontFamily(lang),
            "text-size": {
                stops: [
                    [15, 10],
                    [20, 11],
                ],
            },
            "icon-image": "{subclass}",
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "text-anchor": "top",
            "text-offset": [0, 1],
            "text-padding": 2,
            "text-max-width": 9,
            "icon-allow-overlap": false,
        },
        paint: {
            "text-color": "#C77400",
            "icon-opacity": 1,
            "icon-halo-blur": 1,
            "text-halo-blur": 0.5,
            "icon-halo-color": "rgba(255, 255, 255, 1)",
            "icon-halo-width": 0.5,
            "text-halo-color": "#ffffff",
            "text-halo-width": 1,
        },
        metadata: {},
        filter: ["all", ["in", "class", "ice_cream", "cafe", "beer", "bar", "fast_food", "restaurant"]],
    },
    {
        id: "poi_water",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "poi",
        minzoom: 16,
        layout: {
            "text-font": theme.text.fontFamily(lang),
            "text-size": {
                stops: [
                    [15, 10],
                    [20, 11],
                ],
            },
            "icon-image": "{subclass}",
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "text-anchor": "top",
            "text-offset": [0, 1.2],
            "text-padding": 2,
            "text-max-width": 9,
            "icon-allow-overlap": false,
        },
        paint: {
            "text-color": "#4d80b3",
            "icon-opacity": 1,
            "icon-halo-blur": 1,
            "text-halo-blur": 0.5,
            "icon-halo-color": "rgba(255, 255, 255, 1)",
            "icon-halo-width": 0.5,
            "text-halo-color": "#ffffff",
            "text-halo-width": 1,
        },
        metadata: {},
        filter: ["all", ["in", "class", "ice_rink"]],
    },
    {
        id: "poi_public",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "poi",
        minzoom: 0,
        layout: {
            "text-font": theme.text.fontFamily(lang),
            "text-size": {
                stops: [
                    [15, 10],
                    [20, 11],
                ],
            },
            "icon-image": "{subclass}",
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "text-anchor": "top",
            "text-offset": [0, 0.8],
            "text-padding": 2,
            "text-max-width": 9,
            "icon-allow-overlap": false,
        },
        paint: {
            "text-color": "#734a08",
            "icon-opacity": 1,
            "icon-halo-blur": 1,
            "text-halo-blur": 0.5,
            "icon-halo-color": "rgba(255, 255, 255, 1)",
            "icon-halo-width": 0.5,
            "text-halo-color": "#ffffff",
            "text-halo-width": 1,
        },
        metadata: {},
        filter: ["all", ["in", "class", "town_hall", "post", "library", "police", "information", "cinema", "theatre", "fire_station"], ["!=", "subclass", "books"]],
    },
    {
        id: "poi_cultural",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "poi",
        minzoom: 0,
        layout: {
            "text-font": theme.text.fontFamily(lang),
            "text-size": {
                stops: [
                    [15, 10],
                    [20, 11],
                ],
            },
            "icon-image": "{subclass}",
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "text-anchor": "top",
            "text-offset": [0, 0.8],
            "text-padding": 2,
            "text-max-width": 9,
            "icon-allow-overlap": false,
        },
        paint: {
            "text-color": "#734a08",
            "icon-opacity": 1,
            "icon-halo-blur": 1,
            "text-halo-blur": 0.5,
            "icon-halo-color": "rgba(255, 255, 255, 1)",
            "icon-halo-width": 0.5,
            "text-halo-color": "#ffffff",
            "text-halo-width": 1,
        },
        metadata: {},
        filter: ["all", ["in", "class", "cinema", "library", "music", "museum", "castle", "monument", "art_gallery"], ["!in", "subclass", "books", "musical_instrument", "art", "gallery"]],
    },
    {
        id: "poi_attraction",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "poi",
        minzoom: 0,
        layout: {
            "text-font": theme.text.fontFamily(lang),
            "text-size": {
                stops: [
                    [15, 10],
                    [20, 11],
                ],
            },
            "icon-image": "{subclass}",
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "text-anchor": "top",
            "text-offset": [0, 1.2],
            "text-padding": 2,
            "text-max-width": 9,
            "icon-allow-overlap": false,
        },
        paint: {
            "text-color": "#660033",
            "icon-opacity": 1,
            "icon-halo-blur": 1,
            "text-halo-blur": 0.5,
            "icon-halo-color": "rgba(255, 255, 255, 1)",
            "icon-halo-width": 0.5,
            "text-halo-color": "#ffffff",
            "text-halo-width": 1,
        },
        metadata: {},
        filter: ["all", ["==", "class", "attraction"]],
    },
    {
        id: "poi_car",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "poi",
        minzoom: 0,
        layout: {
            "text-font": theme.text.fontFamily(lang),
            "text-size": {
                stops: [
                    [15, 10],
                    [20, 11],
                ],
            },
            "icon-image": "{subclass}",
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "text-anchor": "top",
            "text-offset": [0, 1.2],
            "text-padding": 2,
            "text-max-width": 9,
            "icon-allow-overlap": false,
            "icon-ignore-placement": false,
        },
        paint: {
            "text-color": "#0066ff",
            "icon-opacity": 1,
            "icon-halo-blur": 1,
            "text-halo-blur": 0.5,
            "icon-halo-color": "rgba(255, 255, 255, 1)",
            "icon-halo-width": 0.5,
            "text-halo-color": "#ffffff",
            "text-halo-width": 1,
        },
        metadata: {},
        filter: ["all", ["in", "class", "car", "fuel"]],
    },
    {
        id: "poi_campsite",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "poi",
        minzoom: 0,
        layout: {
            "text-font": theme.text.fontFamily(lang),
            "text-size": {
                stops: [
                    [15, 10],
                    [20, 11],
                ],
            },
            "icon-image": "camping",
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "text-anchor": "top",
            "text-offset": [0, 1.2],
            "text-padding": 2,
            "text-max-width": 9,
            "icon-allow-overlap": false,
        },
        paint: {
            "text-color": "#0066ff",
            "icon-opacity": 1,
            "icon-halo-blur": 1,
            "text-halo-blur": 0.5,
            "icon-halo-color": "rgba(255, 255, 255, 1)",
            "icon-halo-width": 0.5,
            "text-halo-color": "#ffffff",
            "text-halo-width": 1,
        },
        metadata: {},
        filter: ["all", ["in", "class", "campsite"]],
    },
    {
        id: "poi_accommodation",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "poi",
        minzoom: 0,
        layout: {
            "text-font": theme.text.fontFamily(lang),
            "text-size": {
                stops: [
                    [15, 10],
                    [20, 11],
                ],
            },
            "icon-image": "{subclass}",
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "text-anchor": "top",
            "text-offset": [0, 0.6],
            "text-padding": 2,
            "text-max-width": 9,
            "icon-allow-overlap": false,
        },
        paint: {
            "text-color": "#0066ff",
            "icon-opacity": 1,
            "icon-halo-blur": 1,
            "text-halo-blur": 0.5,
            "icon-halo-color": "rgba(255, 255, 255, 1)",
            "icon-halo-width": 0.5,
            "text-halo-color": "#ffffff",
            "text-halo-width": 1,
        },
        metadata: {},
        filter: ["all", ["in", "class", "lodging", "campsite"]],
    },
    {
        id: "poi_place_of_worship",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "poi",
        minzoom: 0,
        layout: {
            "icon-size": 1,
            "text-font": theme.text.fontFamily(lang),
            "text-size": {
                stops: [
                    [15, 10],
                    [20, 12],
                ],
            },
            "icon-image": "{subclass}",
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "text-anchor": "top",
            "text-offset": [0, 1.2],
            "text-padding": 2,
            "text-max-width": 9,
            "icon-allow-overlap": false,
            "text-allow-overlap": false,
        },
        paint: {
            "text-color": "rgba(56, 56, 71, 1)",
            "text-halo-blur": 0.5,
            "text-halo-color": "#ffffff",
            "text-halo-width": 1,
        },
        metadata: {},
        filter: ["all", ["==", "class", "place_of_worship"]],
    },
    {
        id: "poi_busstop",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "poi",
        minzoom: 0,
        layout: {
            "icon-size": 1,
            "text-font": theme.text.fontFamily(lang),
            "text-size": {
                stops: [
                    [15, 10],
                    [20, 11],
                ],
            },
            "icon-image": "bus_stop.12",
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "icon-anchor": "bottom",
            "text-anchor": "top",
            "text-padding": 2,
            "icon-text-fit": "none",
            "text-max-width": 14,
            "icon-keep-upright": true,
            "icon-allow-overlap": false,
            "icon-pitch-alignment": "viewport",
        },
        paint: {
            "text-color": "#0066ff",
            "icon-translate": [0, 0],
            "text-translate": [0, 4],
            "text-halo-color": "rgba(255, 255, 255, 1)",
            "text-halo-width": 0.8,
            "icon-translate-anchor": "map",
            "text-translate-anchor": "viewport",
        },
        metadata: {},
        filter: ["all", ["in", "class", "bus"]],
    },
    {
        id: "poi_bus",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "poi",
        minzoom: 0,
        layout: {
            "icon-size": 1,
            "text-font": theme.text.fontFamily(lang),
            "text-size": 11,
            "icon-image": "{subclass}",
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "icon-anchor": "bottom",
            "icon-offset": [0, 0],
            "text-anchor": "center",
            "text-padding": 2,
            "icon-text-fit": "none",
            "text-max-width": 14,
            "icon-keep-upright": true,
            "icon-allow-overlap": false,
            "icon-pitch-alignment": "viewport",
        },
        paint: {
            "text-color": "#0066ff",
            "icon-translate": [0, 0],
            "text-translate": [0, 5],
            "text-halo-color": "rgba(255, 255, 255, 1)",
            "text-halo-width": 0.8,
            "icon-translate-anchor": "map",
            "text-translate-anchor": "viewport",
        },
        metadata: {},
        filter: ["all", ["in", "class", "bus"], ["!in", "subclass", "bus_stop"]],
    },
    {
        id: "poi_harbor",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "poi",
        minzoom: 0,
        layout: {
            "text-font": theme.text.fontFamily(lang),
            "text-size": {
                stops: [
                    [14, 13],
                    [20, 16],
                ],
            },
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "text-anchor": "top",
            "text-padding": 2,
            "text-max-width": 6,
            "icon-allow-overlap": false,
        },
        paint: {
            "text-color": "#576ddf",
            "icon-opacity": 1,
            "icon-halo-blur": 1,
            "text-halo-blur": 0.1,
            "icon-halo-color": "rgba(255, 255, 255, 1)",
            "icon-halo-width": 0.2,
            "text-halo-color": "#ffffff",
            "text-halo-width": 0.3,
        },
        metadata: {},
        filter: ["all", ["==", "class", "harbor"]],
    },
    {
        id: "poi_mall",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "poi",
        minzoom: 0,
        layout: {
            "text-font": theme.text.fontFamily(lang),
            "text-size": {
                stops: [
                    [15, 12],
                    [20, 16],
                ],
            },
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "text-anchor": "top",
            "text-offset": [0, 1.1],
            "text-padding": 2,
            "text-max-width": 9,
            "icon-allow-overlap": false,
        },
        paint: {
            "text-color": "#d11700",
            "icon-opacity": 1,
            "icon-halo-blur": 1,
            "text-halo-blur": 0.5,
            "icon-halo-color": "rgba(255, 255, 255, 1)",
            "icon-halo-width": 0.5,
            "text-halo-color": "#ffffff",
            "text-halo-width": 1,
        },
        metadata: {},
        filter: ["all", ["==", "class", "shop"], ["==", "subclass", "mall"]],
    },
    {
        id: "poi_train",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "poi",
        minzoom: 12,
        layout: {
            "icon-size": 0.03,
            "text-font": theme.text.fontFamily(lang),
            "text-size": 11,
            "icon-image": "train:train",
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "icon-anchor": "center",
            "text-anchor": "left",
            "text-offset": [1, 0],
            "text-padding": 2,
            "icon-text-fit": "none",
            "text-max-width": 12,
            "icon-allow-overlap": false,
            "text-allow-overlap": false,
            "icon-pitch-alignment": "viewport",
        },
        paint: {
            "text-color": "#4957ad",
            "icon-translate": [0, 0],
            "text-translate": [0, 1],
            "text-halo-color": "rgba(255, 255, 255, 1)",
            "text-halo-width": 0.8,
            "icon-translate-anchor": "map",
            "text-translate-anchor": "viewport",
        },
        metadata: {},
        filter: ["all", ["in", "class", "railway"]],
    },
    {
        id: "road_label",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "transportation_name",
        minzoom: 14,
        layout: {
            "text-font": theme.text.fontFamily(lang),
            "text-size": {
                base: 1,
                stops: [
                    [14, 9],
                    [18, 13],
                ],
            },
            "text-field": theme.text.textField(lang),
            "text-anchor": "center",
            "text-offset": [0, 0],
            "symbol-placement": "line",
        },
        paint: {
            "text-color": "#000000",
            "text-halo-color": "rgba(255, 255, 255, 0.97)",
            "text-halo-width": 1,
        },
        metadata: {},
        filter: ["all", ["!=", "subclass", "ferry"]],
    },
    {
        id: "airport-label-major",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "aerodrome_label",
        minzoom: 8,
        maxzoom: 17,
        layout: {
            "icon-size": 1,
            "text-font": theme.text.fontFamily(lang),
            "text-size": {
                stops: [
                    [8, 10],
                    [14, 12],
                ],
            },
            "icon-image": "aerodrome.12",
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "text-anchor": "top",
            "text-offset": [0, 0.6],
            "text-padding": 2,
            "text-optional": true,
            "symbol-z-order": "auto",
            "text-max-width": 9,
            "icon-allow-overlap": false,
            "text-allow-overlap": false,
        },
        paint: {
            "text-color": "#5e3b9e",
            "text-halo-blur": 0.5,
            "text-halo-color": "rgba(255, 255, 255, 0.8)",
            "text-halo-width": 1,
        },
        filter: ["all", ["has", "iata"]],
    },
    {
        id: "airport_label",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "aeroway",
        minzoom: 14,
        layout: {
            "text-font": theme.text.fontFamily(lang),
            "text-size": {
                stops: [
                    [15, 9],
                    [19, 15],
                ],
            },
            "text-field": "{ref}",
            visibility: "visible",
            "symbol-placement": "line",
        },
        paint: {
            "text-color": "#333333",
            "text-halo-color": "rgba(255, 255, 255, 0.8)",
            "text-halo-width": 1,
        },
        filter: ["all", ["in", "class", "runway", "taxiway"]],
    },
    {
        id: "airport_gate",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "aeroway",
        minzoom: 16.5,
        layout: {
            "text-font": theme.text.fontFamily(lang),
            "text-size": {
                stops: [
                    [17, 9],
                    [19, 15],
                ],
            },
            "text-field": "{ref}",
            visibility: "visible",
        },
        paint: {
            "text-color": "rgba(135, 135, 135, 1)",
            "text-halo-color": "rgba(255, 255, 255, 1)",
            "text-halo-width": 1,
        },
        filter: ["all", ["==", "class", "gate"]],
    },
    {
        id: "place_other",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "place",
        minzoom: 8,
        layout: {
            "text-font": theme.text.fontFamily(lang),
            "text-size": {
                base: 1.2,
                stops: [
                    [11, 10],
                    [14, 14],
                    [18, 16],
                ],
            },
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "symbol-spacing": 150,
            "text-max-width": 10,
            "text-transform": "none",
        },
        paint: {
            "text-color": {
                stops: [
                    [12.5, "#222222"],
                    [12.6, "#777777"],
                ],
            },
            "text-halo-blur": 0,
            "text-halo-color": {
                stops: [
                    [11, "rgba(255,255,255,0.6)"],
                    [13, "#ffffff"],
                ],
            },
            "text-halo-width": {
                stops: [
                    [8, 0.8],
                    [13, 1.5],
                ],
            },
        },
        metadata: {},
        filter: ["all", ["in", "class", "hamlet", "island", "islet", "neighbourhood", "suburb", "borough"]],
    },
    {
        id: "park-local",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "poi",
        minzoom: 15,
        layout: {
            "text-font": theme.text.fontFamily(lang),
            "text-size": {
                stops: [
                    [15, 10],
                    [20, 13],
                ],
            },
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "symbol-spacing": 150,
            "text-max-width": {
                stops: [
                    [12, 5],
                    [18, 8],
                ],
            },
            "text-allow-overlap": false,
        },
        paint: {
            "text-color": "#0c8416",
            "text-halo-blur": 0.5,
            "text-halo-color": "rgba(255, 255, 255, 1)",
            "text-halo-width": 1,
        },
        filter: ["all", ["==", "class", "park"], ["==", "subclass", "park"]],
    },
    {
        id: "park-national",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "park",
        minzoom: 7,
        maxzoom: 12,
        layout: {
            "text-font": theme.text.fontFamily(lang),
            "text-size": 12,
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "symbol-spacing": 150,
            "text-allow-overlap": false,
        },
        paint: {
            "text-color": {
                stops: [
                    [7, "rgba(70, 164, 70, 1)"],
                    [10, "#008000"],
                ],
            },
            "text-halo-blur": 0.1,
            "text-halo-color": {
                stops: [
                    [7, "rgba(241, 255, 234, 1)"],
                    [10, "rgba(208, 250, 200, 1)"],
                ],
            },
            "text-halo-width": 0.3,
        },
        filter: ["all", ["<=", "rank", 2]],
    },
    {
        id: "poi_zoo",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "poi",
        minzoom: 11,
        layout: {
            "text-font": theme.text.fontFamily(lang),
            "text-size": {
                stops: [
                    [15, 12],
                    [20, 16],
                ],
            },
            "icon-image": "{subclass}",
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "text-anchor": "top",
            "text-offset": [0, 1.2],
            "text-padding": 2,
            "text-max-width": 6,
            "icon-allow-overlap": true,
        },
        paint: {
            "text-color": "#660033",
            "icon-opacity": 1,
            "icon-halo-blur": 1,
            "text-halo-blur": 0.5,
            "icon-halo-color": "rgba(255, 255, 255, 1)",
            "icon-halo-width": 0.5,
            "text-halo-color": "#ffffff",
            "text-halo-width": 1,
        },
        metadata: {},
        filter: ["all", ["==", "class", "zoo"], ["==", "subclass", "zoo"]],
    },
    {
        id: "place_village",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "place",
        minzoom: 10,
        layout: {
            "text-font": theme.text.fontFamily(lang),
            "text-size": {
                base: 1.2,
                stops: [
                    [10, 10],
                    [15, 16],
                ],
            },
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "text-max-width": 8,
        },
        paint: {
            "text-color": theme.textColor.default,
            "text-halo-color": "rgba(255,255,255,0.8)",
            "text-halo-width": 1.2,
        },
        metadata: {},
        filter: ["all", ["==", "class", "village"]],
    },
    {
        id: "place_town",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "place",
        minzoom: 10,
        layout: {
            "text-font": theme.text.fontFamily(lang),
            "text-size": {
                base: 1.2,
                stops: [
                    [7, 10],
                    [11, 13],
                ],
            },
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "text-anchor": "bottom",
            "text-offset": [0, 0],
            "text-max-width": 8,
        },
        paint: {
            "text-color": theme.textColor.default,
            "text-halo-color": "rgba(255,255,255,0.8)",
            "text-halo-width": 1.2,
        },
        metadata: {},
        filter: ["all", ["==", "class", "town"]],
    },
    {
        id: "place_state",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "place",
        minzoom: 4,
        maxzoom: 12,
        layout: {
            "text-font": theme.text.fontFamily(lang),
            "text-size": {
                stops: [
                    [3, 10],
                    [6, 14],
                ],
            },
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "text-padding": 2,
            "text-transform": "none",
            "text-letter-spacing": 0,
        },
        paint: {
            "text-color": theme.textColor.default,
            "text-halo-color": "rgba(255,255,255,0.7)",
            "text-halo-width": 0.8,
        },
        metadata: {},
        filter: ["all", ["==", "class", "state"], ["<", "rank", 3]],
    },
    {
        id: "place_city",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "place",
        minzoom: 4,
        maxzoom: 14,
        layout: {
            "text-font": theme.text.fontFamily(lang),
            "text-size": {
                base: 1.2,
                stops: [
                    [4, 12],
                    [15, 18],
                ],
            },
            "icon-image": {
                stops: [
                    [4, "place-6"],
                    [7, " "],
                ],
            },
            "text-field": theme.text.textField(lang),
            visibility: "visible",
            "icon-offset": [0, 3],
            "text-anchor": "bottom",
            "text-offset": [0, 0],
            "icon-optional": false,
            "text-max-width": 8,
            "icon-allow-overlap": true,
        },
        paint: {
            "text-color": theme.textColor.default,
            "text-halo-color": "rgba(255,255,255,0.8)",
            "text-halo-width": 1,
        },
        metadata: {},
        filter: ["all", ["==", "class", "city"], ["!=", "rank", 1]],
    },
];

export default labelLayers;
