import { Zen_Maru_Gothic } from "next/font/google";
import "./globals.css";

const zenMaruGothic = Zen_Maru_Gothic({
    variable: "--font-zen-maru-gothic",
    subsets: ["latin"],
    weight: ["400"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="ja">
            <body className={`${zenMaruGothic.variable} antialiased`}>{children}</body>
        </html>
    );
}
